/* 389. Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters. */

// My Solution 

func findTheDifference(s string, t string) byte {
  sHash := make(map[byte]int)
  	tHash := make(map[byte]int)
  
  	for i := 0; i < len(s); i++ {
  		char := s[i]
  		sHash[char]++
  	}
  
  	for i := 0; i < len(t); i++ {
  		char := t[i]
  		tHash[char]++
  	}
  
  	for i := 0; i < len(t); i++ {
  		char := t[i]
  		if tHash[char] > sHash[char] || sHash[char] == 0 {
  			return char
  		}
  	}
  	
  	return 0 
}