/* 389. Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters. */

// My Solution 

function findTheDifference(s, t) {
  let sHash = {}
  let tHash = {}
  let sLen = s.length;
  let tLen = t.length;

  for (let i = 0; i < sLen; i++) {
    let char = s[i]
    sHash[char] = ((sHash[char] || 0) + 1)
  }
  for (let i = 0; i < tLen; i++) {
    let char = t[i]
    tHash[char] = ((tHash[char] || 0) + 1)
  }
  for (let i = 0; i < tLen; i++) {
    let char = t[i]
    if (tHash[char] > sHash[char] || !sHash[char]) return char
  }
}